let PRODUCTS = [];

async function loadProducts() {
  try {
    let response = await fetch('api/products');
    if (!response.ok) response = await fetch('data/products.json');
    if (!response.ok) throw new Error('Product database file not found');
    PRODUCTS = await response.json();
    initializeSite();
  } catch (error) {
    console.error(error);
    toast('Product database could not be loaded');
  }
}

function initializeSite() {
  updateCounts();
  setupSearch();
    setupUpiScanner();
   setupCatalogFilters();
  renderPageProducts();
  renderProductDetails();
  renderCart();
  setupRecommend();
  setupCheckout();
  setupOrders();
  setupAdmin();
  document.querySelectorAll('[data-newsletter]').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); form.reset(); toast('You are on the gifting list'); }));
}
  function setupUpiScanner() { 
    const option = document.querySelector('input[name="payment"][value="UPI (Demo)"]'); 
    if (!option) return; 
    const choice = option.closest('.payment-choice'); 
    const scanner = document.createElement('div'); 
    scanner.className = 'upi-scanner'; 
    scanner.innerHTML = '<span class="upi-label">Demo UPI scanner</span><img src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=upi%3A%2F%2Fpay%3Fpa%3Dgiftgenie%40upi%26pn%3DGiftGenie%26am%3D1" alt="Demo UPI QR code"><strong>giftgenie@upi</strong><small>Scan to preview payment flow. No real payment will be processed.</small>'; 
    choice.insertAdjacentElement('afterend', scanner); 
    option.addEventListener('change', () => scanner.classList.toggle('show', option.checked)); 
  }

const get = key => JSON.parse(localStorage.getItem(key) || '[]');
const set = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const cart = () => get('giftgenie-cart');
const money = value => `₹${Number(value).toLocaleString('en-IN')}`;
const product = id => PRODUCTS.find(item => item.id === Number(id));
function setupCatalogFilters() { const categorySelect = document.querySelector('#categoryFilter'); const occasionSelect = document.querySelector('#occasionFilter'); const intro = document.querySelector('.page-hero p'); if (!categorySelect || !occasionSelect) return; if (intro) intro.textContent = 'Explore thoughtful gifts by price and discover something special.'; const params = new URLSearchParams(location.search); const categories = [...new Set(PRODUCTS.map(item => item.category).filter(Boolean))].sort(); const occasions = [...new Set(PRODUCTS.map(item => item.occasion).filter(Boolean))].sort(); categorySelect.innerHTML = '<option value="">All categories</option>' + categories.map(value => `<option value="${value}">${value}</option>`).join(''); occasionSelect.innerHTML = '<option value="">All occasions</option>' + occasions.map(value => `<option value="${value}">${value}</option>`).join(''); categorySelect.value = params.get('category') || ''; occasionSelect.value = params.get('occasion') || ''; }
function toast(message) { const node = document.querySelector('[data-toast]'); if (!node) return; node.textContent = message; node.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => node.classList.remove('show'), 2200); }
function updateCounts() { document.querySelectorAll('[data-cart-count]').forEach(node => node.textContent = `(${cart().reduce((sum, item) => sum + item.quantity, 0)})`); document.querySelectorAll('[data-saved-count]').forEach(node => node.textContent = `(${get('giftgenie-saved').length})`); }
function addToCart(id, quantity = 1) { const items = cart(); const existing = items.find(item => item.id === Number(id)); if (existing) existing.quantity += quantity; else items.push({ id: Number(id), quantity }); set('giftgenie-cart', items); updateCounts(); toast(`${product(id).name} added to cart`); }
function productCard(item) { const saved = get('giftgenie-saved').includes(item.id); return `<article class="product-card"><button class="save ${saved ? 'saved' : ''}" data-save="${item.id}">${saved ? '♥' : '♡'}</button><a href="product.html?id=${item.id}"><img src="${item.image}" alt="${item.name}" loading="lazy"></a><div class="info"><div class="stars">★★★★★ <span>${item.rating}</span></div><h3>${item.name}</h3><div class="price">${money(item.price)}</div><div class="card-actions"><button data-cart="${item.id}">Add to Cart</button><a href="product.html?id=${item.id}">Details</a></div></div></article>`; }
function bindCards() { document.querySelectorAll('[data-cart]').forEach(node => node.addEventListener('click', event => { event.preventDefault(); addToCart(node.dataset.cart); })); document.querySelectorAll('[data-save]').forEach(node => node.addEventListener('click', event => { event.preventDefault(); const saved = get('giftgenie-saved'); const id = Number(node.dataset.save); const index = saved.indexOf(id); if (index === -1) saved.push(id); else saved.splice(index, 1); set('giftgenie-saved', saved); updateCounts(); renderPageProducts(); toast(index === -1 ? 'Gift saved to wishlist' : 'Gift removed from wishlist'); })); }
function renderPageProducts() { const grid = document.querySelector('[data-product-grid]'); if (!grid) return; let items = PRODUCTS; const params = new URLSearchParams(location.search); const query = (params.get('q') || '').toLowerCase(); const category = (params.get('category') || '').toLowerCase(); const occasion = (params.get('occasion') || '').toLowerCase(); const recipient = (params.get('recipient') || '').toLowerCase(); if (query) items = items.filter(item => `${item.name} ${item.description}`.toLowerCase().includes(query)); if (category) items = items.filter(item => String(item.category).toLowerCase() === category); if (occasion) items = items.filter(item => String(item.occasion).toLowerCase() === occasion); if (recipient) items = items.filter(item => String(item.recipient).toLowerCase() === recipient); const min = Number(params.get('min') || 0); const max = Number(params.get('max') || Infinity); items = items.filter(item => item.price >= min && item.price <= max); if (!items.length && PRODUCTS.length) { items = PRODUCTS; toast('No exact matches, showing all gifts'); } const limit = Number(grid.dataset.limit || items.length); grid.innerHTML = items.slice(0, limit).map(productCard).join('') || '<p class="empty-state">No gifts are available yet.</p>'; bindCards(); }
function setupSearch() { document.querySelectorAll('[data-search-form]').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); const query = new FormData(form).get('q'); location.href = `gifts.html?q=${encodeURIComponent(query)}`; })); }
function renderProductDetails() { const node = document.querySelector('[data-product-detail]'); if (!node) return; const item = product(new URLSearchParams(location.search).get('id')) || PRODUCTS[0]; node.innerHTML = `<div class="detail-image"><img src="${item.image}" alt="${item.name}"></div><div class="detail-copy"><span class="script-label">Thoughtfully chosen for you</span><h1>${item.name}</h1><div class="detail-rating">★★★★★ <span>${item.rating} rating</span></div><div class="detail-price">${money(item.price)}</div><p>${item.description}</p><ul><li>Premium gift-ready packaging</li><li>Available quantity: In stock</li><li>Ships across India in 3–5 days</li></ul><div class="quantity"><button data-minus>-</button><strong data-quantity>1</strong><button data-plus>+</button></div><button class="pink-button" data-detail-cart="${item.id}">Add to Cart →</button><a class="buy-link" href="cart.html">View Cart</a></div>`; let quantity = 1; node.querySelector('[data-minus]').addEventListener('click', () => { quantity = Math.max(1, quantity - 1); node.querySelector('[data-quantity]').textContent = quantity; }); node.querySelector('[data-plus]').addEventListener('click', () => { quantity += 1; node.querySelector('[data-quantity]').textContent = quantity; }); node.querySelector('[data-detail-cart]').addEventListener('click', () => addToCart(item.id, quantity)); }
function renderCart() { const list = document.querySelector('[data-cart-list]'); if (!list) return; const items = cart(); const detailed = items.map(item => ({ ...item, product: product(item.id) })).filter(item => item.product); list.innerHTML = detailed.length ? detailed.map(item => `<article class="cart-row"><img src="${item.product.image}" alt="${item.product.name}"><div><h3>${item.product.name}</h3><p>${money(item.product.price)} each</p></div><div class="quantity"><button data-cart-minus="${item.id}">−</button><strong>${item.quantity}</strong><button data-cart-plus="${item.id}">+</button></div><b>${money(item.product.price * item.quantity)}</b><button class="remove" data-remove="${item.id}">×</button></article>`).join('') : '<div class="empty-state">Your cart is waiting for something thoughtful.</div>'; const subtotal = detailed.reduce((sum, item) => sum + item.product.price * item.quantity, 0); document.querySelectorAll('[data-subtotal]').forEach(node => node.textContent = money(subtotal)); document.querySelectorAll('[data-total]').forEach(node => node.textContent = money(subtotal ? subtotal + 50 : 0)); list.querySelectorAll('[data-remove]').forEach(node => node.addEventListener('click', () => { set('giftgenie-cart', items.filter(item => item.id !== Number(node.dataset.remove))); renderCart(); updateCounts(); })); list.querySelectorAll('[data-cart-minus]').forEach(node => node.addEventListener('click', () => changeQuantity(node.dataset.cartMinus, -1))); list.querySelectorAll('[data-cart-plus]').forEach(node => node.addEventListener('click', () => changeQuantity(node.dataset.cartPlus, 1))); }
function changeQuantity(id, delta) { const items = cart(); const item = items.find(row => row.id === Number(id)); item.quantity += delta; if (item.quantity < 1) set('giftgenie-cart', items.filter(row => row.id !== Number(id))); else set('giftgenie-cart', items); renderCart(); updateCounts(); }
function setupRecommend() { const form = document.querySelector('[data-recommend-form]'); if (!form) return; form.addEventListener('submit', event => { event.preventDefault(); const data = new FormData(form); const recipient = String(data.get('recipient') || '').toLowerCase(); const occasion = String(data.get('occasion') || '').toLowerCase(); const budget = data.get('budget'); const values = { under: [0, 499], '500': [500, 999], '1000': [1000, 1999], '2000': [2000, 999999] }; const [min, max] = values[budget] || [0, Infinity]; const matches = (items, useBudget = true) => items.filter(item => (!recipient || String(item.recipient).toLowerCase() === recipient) && (!occasion || String(item.occasion).toLowerCase() === occasion) && (!useBudget || (item.price >= min && item.price <= max))); let candidates = matches(PRODUCTS); if (!candidates.length) candidates = matches(PRODUCTS, false); if (!candidates.length) candidates = PRODUCTS.filter(item => !recipient || String(item.recipient).toLowerCase() === recipient); if (!candidates.length) candidates = PRODUCTS.filter(item => !occasion || String(item.occasion).toLowerCase() === occasion); if (!candidates.length) candidates = PRODUCTS; candidates.sort((a, b) => Math.abs(a.price - max) - Math.abs(b.price - max) || b.rating - a.rating); location.href = `product.html?id=${candidates[0].id}&recommended=1`; }); }
function setupCheckout() { const form = document.querySelector('[data-checkout-form]'); if (!form) return; form.addEventListener('submit', async event => { event.preventDefault(); const submit = form.querySelector('button[type="submit"]'); if (submit) submit.disabled = true; const data = Object.fromEntries(new FormData(form)); const items = cart().map(item => ({ productId: item.id, quantity: item.quantity })); const order = { id: `GG${Date.now().toString().slice(-6)}`, ...data, items, date: new Date().toLocaleDateString(), status: 'Pending' }; try { const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(order) }); if (!response.ok) throw new Error('Order could not be saved'); const saved = await response.json(); const orders = get('giftgenie-orders'); orders.push(saved.order || order); set('giftgenie-orders', orders); set('giftgenie-cart', []); const modal = document.querySelector('[data-success-modal]'); const message = document.querySelector('[data-success-message]'); const continueButton = document.querySelector('[data-success-continue]'); if (message) message.textContent = `Order ${saved.order?.id || order.id} has been saved successfully.`; if (modal) modal.classList.add('show'); if (continueButton) continueButton.addEventListener('click', () => { location.href = 'orders.html?success=1'; }); } catch (error) { console.error(error); if (submit) submit.disabled = false; toast('Could not save the order. Please start the project server and try again.'); } }); }
function setupOrders() { const list = document.querySelector('#ordersList'); if (!list) return; fetch('/api/orders').then(response => { if (!response.ok) throw new Error('Orders could not be loaded'); return response.json(); }).then(orders => { set('giftgenie-orders', orders); list.innerHTML = orders.length ? orders.slice().reverse().map(order => `<article class="order-card"><div class="order-card-head"><div><span class="order-label">Order placed</span><span class="order-number">${order.id}</span><p>${order.date} · ${order.payment}</p></div><span class="status">${order.status}</span></div><div class="order-products">${(order.items || []).map(item => `<div class="order-product"><img src="${item.image}" alt="${item.name}"><div class="order-product-info"><h3>${item.name}</h3><p>Quantity: ${item.quantity}</p><span>${money(item.price)} each</span></div><strong>${money(item.lineTotal)}</strong></div>`).join('')}</div><div class="order-card-foot"><div><span>Delivering to</span><strong>${order.name}</strong><p>${order.address}, ${order.city} · ${order.pincode}</p></div><div class="order-total"><span>Order total</span><strong>${money(order.total)}</strong></div></div></article>`).join('') : '<div class="empty-state"><h3>No orders yet</h3><p>Your next thoughtful gift will appear here.</p><a class="pink-button" href="gifts.html">Browse gifts →</a></div>'; }).catch(error => { console.error(error); list.innerHTML = '<div class="empty-state"><h3>Orders could not be loaded</h3><p>Start the project server and try again.</p></div>'; }); }
function setupAdmin() { const form = document.querySelector('[data-admin-product]'); if (!form) return; const custom = get('giftgenie-custom-products'); form.addEventListener('submit', event => { event.preventDefault(); custom.push({ id: Date.now(), name: form.name.value, price: Number(form.price.value), category: form.category.value, occasion: 'Just Because', recipient: 'General', rating: 5, image: form.image.value || PRODUCTS[0].image, description: form.description.value }); set('giftgenie-custom-products', custom); form.reset(); toast('Product added to catalog'); }); }
loadProducts();
